### ISSUE TITLE
Documentation: Insight Application GUI requires Win7 64-bit edition

### ISSUE THREAD

**Issue by kennwhite** [MicrochipTech/AWS-Secure-Insight#1]
Documentation update requested. The requirements here:
https://github.com/MicrochipTech/AWS-Secure-Insight#required-tools-and-applications

and here:
In https://github.com/MicrochipTech/AWS-Secure-Insight/wiki/Installing-the-AWS-IoT-Zero-Touch-GUI 

do not mention that Win7 64-bit is required. The bundled Application GUI exe (Insight.exe) does not start under 32-bit edition of either Microsoft's Test VM Win7x32/IE11 (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) or full installs of Win7 Pro or Enterprise 32-bit. Error message was "incompatible with this version of Windows".

Stating the explicit system requirements in the Wiki and Readme would be very useful, including any recommendations for setting up test environments in a Windows VM.

**Comment by oscarmicrochip** [comment]
Currently only Windows 64bit versions are supported. Work is being done to support

Windows 32 bit versions
MAC OS 
Linux

Regards
Oscar
