### ISSUE TITLE
Unsigned driver is required to install Insight Thing security hardware

### ISSUE THREAD

**Issue by kennwhite** [MicrochipTech/AWS-Secure-Insight#2]
Strongly recommend adding an official Microsoft signed driver for the ATMEL ASF CDC controller (COM3 emulator). Also, the documentation should be more clear for developers using a Windows VM, as the USB passthrough behavior is blocking in getting a working setup.

Steps to reproduce:
1. Using fully updated & patched OSX El Capitan 10.11.5 host
2. Install latest VirtualBox Version 5.1.2 r108956 for OSX
3. Install VirtualBox Extensions for 5.1.2
4. Create a new VM with: Win7 Ultimate N x64
5. Run all Windows updates (recommend https://www.microsoft.com/en-us/download/details.aspx?id=49540 to accelerate update process, as described here: http://superuser.com/a/996072) 
6. Unzip application with 7-Zip. As described in Wiki, moving to: C:\MicroCh\GUI and C:\MicroCh\FW, respectively
7. Create desktop shortcut to C:\MicroCh\GUI\Insight.exe
8. Insert AWS Root dongle
9. Enable USB/Microchip AWS Root Dongle in the VM menu Devices
10. Win7 USB install wizard completes successfully
11. Enable USB/Microchip AWS Signer dongle in the VM menu Devices
12. Win7 USB install wizard completes successfully
13. Enable USB/ATMEL ASF CDC
14. Win7 install wizard unable to complete, "No device driver found"
15. Open Device Manager
16. Navigate to Other Devices (with ! icon)
17. Attempt Windows automatically find driver, fail
18. Attempt Search this computer, fail
19. Windows Security red warning popup: Windows can't verity the publisher of this driver software 
20. Click Install this driver software anyway
21. Specify C:\MicroCh ("All subdirectories" checked)
22. Windows has successfully update your driver software. Windows has finished installing the driver software for this device: Communication Device Class ASF example
23. Start Insight executable

Both the Root and Signer are recognized, as is the AWS Thing.

**Comment by kennwhite** [comment]
![usb_passthrough](https://cloud.githubusercontent.com/assets/326990/17706851/b6957de4-63ab-11e6-95f9-998d15e9c744.png)
![untrusted driver warning](https://cloud.githubusercontent.com/assets/326990/17706873/c96834e8-63ab-11e6-970a-e1b11867d45b.png)
![usb_2_ehci_enabled](https://cloud.githubusercontent.com/assets/326990/17706877/cd22a24e-63ab-11e6-9a1f-6303e7f9c2c0.png)
![insight_device_driver](https://cloud.githubusercontent.com/assets/326990/17706887/d304203e-63ab-11e6-8e9e-1b4927b1c3ea.png)

**Comment by oscarmicrochip** [comment]
Guidance has been added to the documentation on how to bridge the driver to the VM
