### ISSUE TITLE
Not able to identify USB Root/Signer and Thing

### ISSUE THREAD

**Issue by etienne-bechara** [MicrochipTech/AWS-Secure-Insight#4]
I'm following the tutorial to run the demo kit, but when I click on "Re-Scan connections" the information below is not filled up.

There is no unknown devices at device manager and I tried both in Windows 7 and 10.

Any ideas?

**Comment by schielimicrochip** [comment]
Thanks for reaching out.

Could you provide a copy of the log from the AWS Secure Insight application?
Are the Root and Signer dongles visible in the device manager?

Regards
Nicolas

**Comment by etienne-bechara** [comment]
Thanks for helping.

Here is the log: [http://imgur.com/a/2FHeC](http://imgur.com/a/2FHeC)

And the device manager: [http://imgur.com/a/nXeGO](http://imgur.com/a/nXeGO)

I think it is not recognizing them at all.

**Comment by schielimicrochip** [comment]
Indeed, the dongles are not enumerated on your system.

Could you please contact us directly at:
Nicolas.schieli@microchip.commailto:Nicolas.schieli@microchip.com
Oscar.sanchez@microchip.commailto:Oscar.sanchez@microchip.com

Regards
Nicolas

**Comment by cdurante** [comment]
Same issue. What was the solution?

**Comment by etienne-bechara** [comment]
I received the dongles from another kit.

I have attached the full thread that was supported via mail, hope it helps.


[RE AWS-Secure-Insight Issue.zip](https://github.com/MicrochipTech/AWS-Secure-Insight/files/974407/RE.AWS-Secure-Insight.Issue.zip)

**Comment by cdurante** [comment]
Thanks! I fell into the same confusion.
